from setuptools import setup, find_packages

setup(
    name="stockstorm",
    version="2.0.0",
    packages=find_packages(),
    include_package_data=True,
    install_requires=[
        'Django>=4.2.3,<5.0.0',
        'django-rest-framework>=0.1.0',
        'djangorestframework>=3.14.0',
        'websocket-client>=1.6.1',
        'numpy>=1.24.3',
        'pandas>=2.0.2',
        'requests>=2.31.0',
        'python-binance>=1.0.19',
        'cryptography>=41.0.1',
        'pytz>=2023.3',
        'Pillow>=10.0.0',
        'whitenoise>=6.5.0',
        'psycopg2-binary>=2.9.6',
        'dj-database-url>=2.0.0',
        'gunicorn>=21.2.0',
        'python-telegram-bot>=20.4',
        'twilio>=7.12.0',
        'django-redis>=5.2.0',
        'redis>=4.6.0',
        'django-prometheus>=2.3.0',
        'mysqlclient>=2.1.0',
        'channels>=4.0.0',
        'daphne>=4.0.0',
        'channels-redis>=4.1.0',
        'asgiref>=3.7.2',
        'emoji>=2.10.0',
        'markdown2>=2.4.10',
        'bleach>=6.1.0',
        'django-cors-headers>=4.3.1',
        'matplotlib>=3.7.1',
        'openai>=1.2.0',
    ],
    description="Django-based microservice for automated cryptocurrency trading",
    author="desu777",
    author_email="contact@stockstorm.com",
    classifiers=[
        'Development Status :: 4 - Beta',
        'Environment :: Web Environment',
        'Framework :: Django',
        'Intended Audience :: Financial and Insurance Industry',
        'License :: OSI Approved :: MIT License',
        'Operating System :: OS Independent',
        'Programming Language :: Python',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.9',
        'Programming Language :: Python :: 3.10',
        'Topic :: Office/Business :: Financial :: Investment',
    ],
    python_requires='>=3.9',
)
