# Generated by Django 5.1.4 on 2025-03-16 16:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broker_type', models.CharField(choices=[('BNB', 'Binance')], default='BNB', max_length=3)),
                ('name', models.CharField(max_length=100)),
                ('instrument', models.CharField(max_length=50)),
                ('max_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('percent', models.IntegerField()),
                ('capital', models.DecimalField(decimal_places=2, max_digits=12)),
                ('stream_session_id', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('RUNNING', 'Running'), ('FINISHED', 'Finished'), ('ERROR', 'Error')], default='NEW', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('microservice_bot_id', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TelegramConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(help_text='Telegram chat ID for notifications', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verification_code', models.CharField(blank=True, help_text='Temporary code for verifying Telegram account ownership', max_length=32, null=True)),
                ('is_verified', models.BooleanField(default=False, help_text='Whether the Telegram chat ID has been verified')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_config', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('binance_api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('binance_api_secret_enc', models.BinaryField(blank=True, null=True)),
                ('telegram_notifications_enabled', models.BooleanField(default=False, verbose_name='Enable Telegram Notifications')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
