# Generated by Django 5.1.4 on 2025-03-16 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether the bot is active or not'),
        ),
        migrations.AddField(
            model_name='bot',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
