# Generated by Django 5.1.4 on 2025-03-17 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_botlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='total_profit',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total profit accumulated by this bot', max_digits=15),
        ),
    ]
