# Generated by Django 5.1.4 on 2025-03-04 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hpcrypto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricealert',
            name='last_notification_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pricealert',
            name='notification_sent',
            field=models.BooleanField(default=False),
        ),
    ]
