# Generated by Django 5.1.4 on 2025-03-04 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hpcrypto', '0002_pricealert_last_notification_sent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricealert',
            name='sms_sent',
            field=models.BooleanField(default=False),
        ),
    ]
