# Generated by Django 5.1.4 on 2025-03-05 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hpcrypto', '0004_pricealert_notify_push_pricealert_notify_telegram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricealert',
            name='notify_push',
            field=models.BooleanField(default=False, help_text='Send push notification when alert triggered'),
        ),
    ]
