# Generated by Django 5.1.4 on 2025-03-22 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hpcrypto', '0007_pricealert_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='exit_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
