# Generated by Django 5.1.4 on 2025-01-26 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BnbBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=50)),
                ('max_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('percent', models.DecimalField(decimal_places=2, default=2.0, max_digits=5)),
                ('capital', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('RUNNING', 'Running'), ('FINISHED', 'Finished'), ('ERROR', 'Error')], default='NEW', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('levels_data', models.TextField(blank=True, null=True)),
                ('binance_api_key', models.CharField(blank=True, max_length=128, null=True)),
                ('binance_api_secret_enc', models.BinaryField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(unique=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('reserved_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('auth_token', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BnbTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=10)),
                ('side', models.CharField(max_length=4)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=14)),
                ('stop_price', models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True)),
                ('limit_price', models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True)),
                ('binance_order_id', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('FILLED', 'Filled')], default='OPEN', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('filled_at', models.DateTimeField(blank=True, null=True)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bnbgrid.bnbbot')),
            ],
        ),
    ]
