# Generated by Django 5.1.4 on 2025-01-26 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnbgrid', '0003_remove_bnbtrade_profit_bnbtrade_limit_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bnbtrade',
            name='profit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
    ]
