# Generated by Django 5.1.4 on 2025-01-26 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bnbgrid', '0004_bnbtrade_profit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bnbtrade',
            name='stop_price',
        ),
    ]
