# Generated by Django 5.1.4 on 2025-01-29 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnbgrid', '0006_bnbtrade_buy_type_bnbtrade_sell_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bnbbot',
            name='capital',
        ),
        migrations.RemoveField(
            model_name='bnbbot',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='bnbbot',
            name='max_price',
        ),
        migrations.RemoveField(
            model_name='bnbbot',
            name='name',
        ),
        migrations.RemoveField(
            model_name='bnbbot',
            name='percent',
        ),
        migrations.RemoveField(
            model_name='bnbtrade',
            name='filled_at',
        ),
        migrations.RemoveField(
            model_name='bnbtrade',
            name='limit_price',
        ),
        migrations.AlterField(
            model_name='bnbbot',
            name='binance_api_key',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bnbbot',
            name='binance_api_secret_enc',
            field=models.BinaryField(default=34234),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bnbbot',
            name='levels_data',
            field=models.TextField(default='{}'),
        ),
        migrations.AlterField(
            model_name='bnbbot',
            name='status',
            field=models.CharField(choices=[('RUNNING', 'Running'), ('STOPPED', 'Stopped')], default='STOPPED', max_length=10),
        ),
        migrations.AlterField(
            model_name='bnbbot',
            name='symbol',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='bnbtrade',
            name='binance_order_id',
            field=models.CharField(default=34324, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bnbtrade',
            name='buy_type',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='bnbtrade',
            name='close_price',
            field=models.DecimalField(decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='bnbtrade',
            name='open_price',
            field=models.DecimalField(decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='bnbtrade',
            name='profit',
            field=models.DecimalField(decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='bnbtrade',
            name='quantity',
            field=models.DecimalField(decimal_places=8, max_digits=20),
        ),
        migrations.AlterField(
            model_name='bnbtrade',
            name='sell_type',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='bnbtrade',
            name='status',
            field=models.CharField(max_length=10),
        ),
    ]
