# Generated by Django 5.1.4 on 2025-01-29 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnbgrid', '0007_remove_bnbbot_capital_remove_bnbbot_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bnbbot',
            name='capital',
            field=models.DecimalField(decimal_places=2, default=545, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bnbbot',
            name='max_price',
            field=models.DecimalField(decimal_places=2, default=435435, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bnbbot',
            name='name',
            field=models.CharField(default=33455, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bnbbot',
            name='percent',
            field=models.DecimalField(decimal_places=2, default=2.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='bnbbot',
            name='symbol',
            field=models.CharField(max_length=50),
        ),
    ]
