# Generated by Django 5.1.4 on 2025-02-01 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnbgrid', '0008_bnbbot_capital_bnbbot_max_price_bnbbot_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bnbbot',
            name='binance_api_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bnbbot',
            name='binance_api_secret_enc',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bnbtrade',
            name='binance_order_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bnbtrade',
            name='bot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='bnbgrid.bnbbot'),
        ),
    ]
